# JMeter user.properties - 默认参数（可通过 -J 覆盖）
threads=50
rampup=3
duration=15
path=/v2/createOptimisticOrder/1
jtl=/tmp/default.jtl

# 输出格式
jmeter.save.saveservice.output_format=csv
jmeter.save.saveservice.assertion_results_failure_message=false
jmeter.save.saveservice.successful=true
jmeter.save.saveservice.elapsed_time=true
jmeter.save.saveservice.latency=true
jmeter.save.saveservice.connect_time=true
jmeter.save.saveservice.bytes=true
jmeter.save.saveservice.sent_bytes=true
jmeter.save.saveservice.thread_name=true
jmeter.save.saveservice.time=true
jmeter.save.saveservice.timestamp_format=ms
jmeter.save.saveservice.response_code=true
jmeter.save.saveservice.thread_counts=true
jmeter.save.saveservice.sample_count=true
